name: Deploy to EC2  
on:
  push:
    branches:
      - main
    paths:
      - "**"
env:
  JAR_FILE_NAME: 'demodeploy.jar'
  TARGET_PATH: ''
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USERNAME : ${{ secrets.EC2_USERNAME }}
  EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATEKEY }}
  
jobs:
  deploy:
    runs-on: ubuntu-lastest

    steps:
    - name : Checkout code
      uses : actions/checkout@v2

    - name : Set up SDK
      uses : actions/setup-java@v2
      with : 
        java-version: '21'
        distribution: 'adopt'

    - name: Build Jar
      run : cd ${{ env.TARGET_PATH }} && mvn package -DskipTests

    - name : Rename Jar
      run : |
        mv ${{ env.TARGET_PATH }}/target/Shopping-0.0.1-SNAPSHOT.jar ${{ env.TARGET_PATH }}/target/${{ env.JAR_FILE_NAME }}

    - name : Copy jar to EC2
      uses : appleboy/scp-action@master
      with :
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_USERNAME }}
        key: ${{ env.EC2_PRIVATE_KEY }}
        source: '${{ env.TARGET_PATH }}/target/${{ env.JAR_FILE_NAME }}' 
        target: '${{ env.TARGET_PATH }}'
    - name : Deploying
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_USERNAME }}
        key: ${{ env.EC2_PRIVATE_KEY }}
        script: |
          {
            if tmux ls | awk -F: '{print &1}' | grep -wp "deployment"; then
              tmux kill-session -t deployment
            fi
          }
          cd ${{ env.TARGET_PATH }}/${{ env.TARGET_PATH }}/target
          tmux new-session -d -s deployment 'java-jar ${{ env.JAR_FILE_NAME }}'
  
  
